server.port=8080
spring.application.name=chess-reviewer-by-Hamid

# Stockfish API Configuration (if using online API)
#stockfish.api.key=${STOCKFISH_API_KEY:}
#stockfish.api.url=https://stockfish.online/api/s/v2.php

# Local Stockfish Configuration (if using local engine)
stockfish.engine.enabled=true
stockfish.engine.path=${STOCKFISH_PATH:stockfish}
stockfish.threads=4
stockfish.hash=1024
stockfish.skill-level=20